---
- name: service | Configuring Alertmanager Service
  ansible.builtin.template:
    src: etc/systemd/system/alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: u=rw,g=r,o=r
  notify:
    - reload systemd
    - restart alertmanager
  become: true
  when: ansible_service_mgr == "systemd"

- name: service | Ensuring Alertmanager Service Is Started and Enabled
  ansible.builtin.service:
    name: alertmanager
    state: started
    enabled: true
  become: true
