---
# handlers file for Alertmanager
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
  become: true

- name: restart alertmanager
  ansible.builtin.service:
    name: alertmanager
    state: restarted
  become: true
